export { default as Layout } from "./Layout"
export { default as Dashboard } from "./Dashboard"
export { default as Product } from "./Product"
export { default as Login } from "./Login"
export { default as AddProduct } from "./AddProduct"